version: "3"

services:
    jenkins:
        user: root
        image: "jenkinsci/blueocean:1.23.1"
        ports:
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
            - mynet
    
networks:
  mynet:
    driver: bridge
